Traceback (most recent call last):
  File "main.py", line 85, in housetest
    q = writeYourRep.writerep(writeYourRep.prepare_i(dist))
  File "/Users/paul/mass-email-delivery-code/WriteYourRep.py", line 128, in prepare_i
    i.addr1 = distAddress['addr1']
KeyError: 'addr1'
Traceback (most recent call last):
  File "main.py", line 85, in housetest
    q = writeYourRep.writerep(writeYourRep.prepare_i(dist))
  File "/Users/paul/mass-email-delivery-code/WriteYourRep.py", line 61, in writerep
    q = self.writerep_general(link, i)
  File "/Users/paul/mass-email-delivery-code/WriteYourRep.py", line 195, in writerep_general
    b.open(contact_link)
  File "/Users/paul/mass-email-delivery-code/browser.py", line 32, in open
    response = opener.open(request, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 386, in open
    protocol = req.get_type()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 248, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: faleomavaega@mail.house.gov
Traceback (most recent call last):
  File "main.py", line 252, in <module>
    housetest()
  File "main.py", line 85, in housetest
    q = writeYourRep.writerep(writeYourRep.prepare_i(dist))
  File "/Users/paul/mass-email-delivery-code/WriteYourRep.py", line 61, in writerep
    q = self.writerep_general(link, i)
  File "/Users/paul/mass-email-delivery-code/WriteYourRep.py", line 363, in writerep_general
    if DEBUG: print "Found error: ", errorStr, " done with ", contact_link
  File "/Users/paul/mass-email-delivery-code/WriteYourRep.py", line 363, in writerep_general
    if DEBUG: print "Found error: ", errorStr, " done with ", contact_link
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
KeyboardInterrupt
